<?php
/**
 * @see IntegerNet_GDM_Block_Form
 * @var $this IntegerNet_GDM_Block_Form
 */
?>

<div class="content-header">
    <h3><?php echo $this->__('German Distribution for Magento') ?></h3>
    <p class="form-buttons">
        <?php echo $this->getButtonHtml($this->__('Save'), 'setupForm.submit();', 'save'); ?>
    </p>
</div>

<p><?php echo $this->__('Please enter your data:') ?></p>

<div class="entry-edit">
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="setup_form">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Shop Data') ?></h4>
            <div class="form-buttons"></div>
        </div>

        <div class="fieldset" id="group_fields">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                    <?php foreach($this->getInputFields() as $field): ?>
                        <tr>
                            <td class="label"><label for="field_<?php echo $field['name'] ?>"><?php echo $field['label'] ?></label></td>
                            <td class="value">
                                <?php if ($field['type'] == 'select'): ?>
                                <select name="field[<?php echo $field['name'] ?>]" id="field_<?php echo $field['label'] ?>" style="width:150px !important;">
                                    <?php $value = $this->getValue($field['name']) ?>
                                    <?php foreach(Mage::getSingleton($field['source_model'])->toOptionArray() as $option): ?>
                                    <option value="<?php echo $option['value'] ?>"<?php if($option['value'] == $value): ?> selected="selected"<?php endif ?>>
                                        <?php echo $option['label'] ?>
                                    </option>
                                    <?php endforeach ?>
                                </select>
                                <?php elseif($field['type'] == 'textarea'): ?>
                                <textarea name="field[<?php echo $field['name'] ?>]" id="field_<?php echo $field['label'] ?>"><?php echo $this->getValue($field['name']) ?></textarea>
                                <?php else: ?>
                                <input type="text" name="field[<?php echo $field['name'] ?>]" id="field_<?php echo $field['label'] ?>"class="input-text" value="<?php echo $this->getValue($field['name']) ?>" />
                                <?php endif ?>
                            </td>
                        </tr>
                    <?php endforeach ?>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('PayPal') ?></h4>
            <div class="form-buttons"></div>
        </div>

        <div class="fieldset" id="group_paypal">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="label"><label for="field_paypal_email"><?php echo $this->__('PayPal Merchant Account Email Address') ?></label></td>
                            <td class="value">
                                <input type="text" name="paypal_email" id="field_paypal_email"class="input-text" value="<?php echo Mage::getStoreConfig('payment/wps_required_settings/business_account') ?>" />
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    setupForm = new varienForm('setup_form', '');
</script>
