<?php
/**
 * @see IntegerNet_GDM_Block_Form
 * @var $this IntegerNet_GDM_Block_Form
 */
?>

<div class="content-header">
    <h3><?php echo $this->__('German Distribution for Magento') ?></h3>
    <p class="form-buttons">
        <?php echo $this->getButtonHtml($this->__('Save'), 'setupForm.submit();', 'save'); ?>
    </p>
</div>

<p><?php echo $this->__('Please enter your data:') ?></p>

<div class="entry-edit">
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="setup_form">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Shop Settings') ?></h4>
            <div class="form-buttons"></div>
        </div>

        <div class="fieldset fieldset-wide" id="group_fields7">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="label"><label for="select_country"><?php echo $this->__('Shipping from') ?></label></td>
                            <td class="value" style="width:160px !important;">
                                <select name="country" id="select_country" style="width:150px !important;">
                                    <option value="de" selected="selected"><?php echo $this->__('Germany')?></option>
                                    <option value="at"><?php echo $this->__('Austria')?></option>
                                    <option value="ch"><?php echo $this->__('Switzerland')?></option>
                                </select>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    setupForm = new varienForm('setup_form', '');
</script>
