<?php
/**
 * @see IntegerNet_GDM_Block_Form
 * @var $this IntegerNet_GDM_Block_Form
 */
?>

<div class="content-header">
    <h3><?php echo $this->__('German Store Configuration for Magento CE') ?></h3>
    <p class="form-buttons">
        <?php echo $this->getButtonHtml(Mage::helper('adminhtml')->__('Save'), 'setupForm.submit();', 'save'); ?>
    </p>
</div>

<p><?php echo $this->__('Please enter your data:') ?></p>

<div class="entry-edit">
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="setup_form">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Shop Data') ?></h4>
            <div class="form-buttons"></div>
        </div>

        <div class="fieldset" id="group_fields">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                    <?php foreach($this->getInputFields() as $field): ?>
                        <tr>
                            <td class="label"><label for="field_<?php echo $field['name'] ?>"><?php echo $field['label'] ?></label></td>
                            <td class="value">
                                <?php if ($field['type'] == 'select'): ?>
                                <select name="field[<?php echo $field['name'] ?>]" id="field_<?php echo $field['label'] ?>" style="width:150px !important;">
                                    <?php $value = $this->getValue($field['name']) ?>
                                    <?php foreach(Mage::getSingleton($field['source_model'])->toOptionArray() as $option): ?>
                                    <option value="<?php echo $option['value'] ?>"<?php if($option['value'] == $value): ?> checked="checked"<?php endif ?>>
                                        <?php echo $option['label'] ?>
                                    </option>
                                    <?php endforeach ?>
                                </select>
                                <?php elseif($field['type'] == 'textarea'): ?>
                                <textarea name="field[<?php echo $field['name'] ?>]" id="field_<?php echo $field['label'] ?>"><?php echo $this->getValue($field['name']) ?></textarea>
                                <?php else: ?>
                                <input type="text" name="field[<?php echo $field['name'] ?>]" id="field_<?php echo $field['label'] ?>"class="input-text" value="<?php echo $this->getValue($field['name']) ?>" />
                                <?php endif ?>
                            </td>
                            <td class="comment">
                                <?php if (isset($field['optional']) && $field['optional']): ?>
                                    (<?php echo $this->__('optional') ?>)
                                <?php endif ?>
                            </td>
                        </tr>
                    <?php endforeach ?>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('PayPal') ?></h4>
            <div class="form-buttons"></div>
        </div>

        <div class="fieldset" id="group_paypal">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="label"><label for="field_paypal_email"><?php echo $this->__('PayPal Merchant Account Email Address') ?></label></td>
                            <td class="value">
                                <input type="text" name="paypal_email" id="field_paypal_email" class="input-text" value="<?php echo Mage::getStoreConfig('paypal/general/business_account') ?>" />
                            </td>
                            <td class="comment">(<?php echo $this->__('optional') ?>)</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Data Transfer') ?></h4>
            <div class="form-buttons"></div>
        </div>

        <div class="fieldset" id="group_datatransfer">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="label" rowspan="3"><label for="field_paypal_email"><?php echo $this->__('Allow Data Transfer') ?></label></td>
                            <td class="value">
                                <input
                                    type="radio"
                                    name="field[admin__germanstoreconfig__datatransfer]"
                                    id="field_datatransfer_none"
                                    value="<?php echo IntegerNet_GermanStoreConfig_Model_Source_Datatransfer::DATATRANSFER_NONE ?>"
                                    <?php if(Mage::getStoreConfig('admin/germanstoreconfig/datatransfer') == IntegerNet_GermanStoreConfig_Model_Source_Datatransfer::DATATRANSFER_NONE): ?>checked="checked"<?php endif ?>
                                />
                                <label for="field_datatransfer_none"><?php echo $this->__('No Data Transfer') ?></label>
                            </td>
                            <td class="comment"></td>
                        </tr>
                        <tr>
                            <td class="value">
                                <input
                                    type="radio"
                                    name="field[admin__germanstoreconfig__datatransfer]"
                                    id="field_datatransfer_basic"
                                    value="<?php echo IntegerNet_GermanStoreConfig_Model_Source_Datatransfer::DATATRANSFER_BASIC ?>"
                                    <?php if(Mage::getStoreConfig('admin/germanstoreconfig/datatransfer') == IntegerNet_GermanStoreConfig_Model_Source_Datatransfer::DATATRANSFER_BASIC): ?>checked="checked"<?php endif ?>
                                />
                                <label for="field_datatransfer_basic"><?php echo $this->__('Minimum Data Transfer (basic)') ?></label>
                            </td>
                            <td class="comment"></td>
                        </tr>
                        <tr>
                            <td class="value">
                                <input
                                    type="radio"
                                    name="field[admin__germanstoreconfig__datatransfer]"
                                    id="field_datatransfer_advanced"
                                    value="<?php echo IntegerNet_GermanStoreConfig_Model_Source_Datatransfer::DATATRANSFER_ADVANCED ?>"
                                    <?php if(Mage::getStoreConfig('admin/germanstoreconfig/datatransfer') == IntegerNet_GermanStoreConfig_Model_Source_Datatransfer::DATATRANSFER_ADVANCED): ?>checked="checked"<?php endif ?>
                                />
                                <label for="field_datatransfer_advanced"><?php echo $this->__('Optimum Data Transfer (advanced)') ?></label>
                            </td>
                            <td class="comment"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    setupForm = new varienForm('setup_form', '');
</script>
