<?php
/**
 * @category    AvS
 * @package     AvS_AdminNotificationAdvanced
 * @author      Andreas von Studnitz <avs@avs-webentwicklung.de>
 */
?>
<?php
/**
 * @var $this AvS_AdminNotificationAdvanced_Block_Toolbar
 */
?>
<?php if ($this->isShow()): ?>
<div class="notification-global">
    <?php
        $sParts = array();

        if ($this->getCriticalCount()):
            $sParts[] = '<span class="critical"><strong>'.$this->getCriticalCount().'</strong> '.$this->__('critical').'</span>';
        endif;

        if ($this->getMajorCount()):
            $sParts[] = '<strong>'.$this->getMajorCount().'</strong> '.$this->__('major');
        endif;

        if ($this->getMinorCount()):
            $sParts[] = '<strong>'.$this->getMinorCount().'</strong> '.$this->__('minor');
        endif;

        if ($this->getNoticeCount()):
            $sParts[] = '<strong>'.$this->getNoticeCount().'</strong> '.$this->__('notice');
        endif;

        $msgStats = '';
        $c = count($sParts);
        for ($i = 0; $i < $c; $i++) {
            $msgStats .= $sParts[$i] . ($i == $c-1 ? '' : ($i == $c-2 ? $this->__(' and ') : ', '));
        }

        $latestNoticeUrl = $this->getLatestNoticeUrl();
    ?>

    <span class="f-right" style="margin-left: 10px;">
        <a href="<?php echo $this->getDeleteAllUrl(); ?>"><?php echo $this->getDeleteAllText(); ?></a>
    </span>
    <span class="f-right" style="margin-left: 10px;">
        <a href="<?php echo $this->getMarkAllReadUrl(); ?>"><?php echo $this->getMarkAllReadText(); ?></a>
    </span>

    <span class="f-right">
        <?php $goToBoxMessage = (!empty($latestNoticeUrl)) ? $this->__('Go to messages inbox') : $this->__('Go to notifications') ?>
        <?php echo $this->__('You have %s unread message(s).', $msgStats) ?> <a href="<?php echo $this->getNoticesInboxUrl() ?>"><?php echo $goToBoxMessage ?></a>
    </span>

    <?php if ($this->isMessageWindowAvailable()): ?>
        <strong class="label clickable" onclick="openMessagePopup()">
    <?php else: ?>
        <strong class="label">
    <?php endif; ?>

    <?php echo $this->__('Latest Message:') ?></strong> <?php echo $this->getLatestNotice() ?>
    <?php if (!empty($latestNoticeUrl)): ?>
        <a href="<?php echo $latestNoticeUrl ?>" onclick="this.target='_blank';"><?php echo $this->__('Read details') ?></a>
    <?php endif; ?>

</div>
<?php endif; ?>
